# Prompt
command_timeout = 3000

palette = "catppuccin_macchiato"

format = """
[░▒▓](surface1)\
[  ](bg:surface1 fg:subtext1)\
[](bg:green fg:surface1)\
$directory\
[](fg:green bg:maroon)\
$git_branch\
$git_status\
[](fg:maroon bg:blue)\
$nodejs\
$rust\
$golang\
$php\
$dotnet\
[](fg:blue bg:sapphire)\
$time\
[ ](fg:sapphire)\
\n$character"""

[directory]
style = "fg:surface0 bg:green"
format = "[ $path ]($style)"
truncation_symbol = "…/"
truncation_length = 4

[directory.substitutions]
"Documents" = "󰧮 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[character]
# Note the use of Catppuccin color 'maroon'
success_symbol = "[[♥](green) ❯](maroon)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[git_branch]
symbol = ""
style = "bg:maroon"
format = '[[ $symbol $branch ](fg:surface0 bg:maroon)]($style)'

[git_status]
style = "bg:maroon"
format = '[[($all_status$ahead_behind )](fg:surface0 bg:maroon)]($style)'

[dotnet]
symbol = "dotnet"
style = "bg:blue"
format = '[[ $symbol ($version) ](fg:surface0 bg:blue)]($style)'

[nodejs]
symbol = ""
style = "bg:blue"
format = '[[ $symbol ($version) ](fg:surface0 bg:blue)]($style)'

[rust]
symbol = ""
style = "bg:blue"
format = '[[ $symbol ($version) ](fg:surface0 bg:blue)]($style)'

[golang]
symbol = ""
style = "bg:blue"
format = '[[ $symbol ($version) ](fg:surface0 bg:blue)]($style)'

[php]
symbol = ""
style = "bg:blue"
format = '[[ $symbol ($version) ](fg:surface0 bg:blue)]($style)'

[time]
disabled = false
time_format = "%R"                                        # Hour:Minute Format
style = "bg:sapphire"
format = '[[  $time ](fg:surface1 bg:sapphire)]($style)'
